language: node_js
node_js:
  - "0.10"
  - "0.11"
addons:
  code_climate:
    repo_token: 6db4bd52612541c2af5e02886b373aba0b8da5f89b26d9e2cb0831dacd06b163
after_script:
  - "npm run coveralls"
  - "npm run codeclimate"
